ARG VERSION=master
FROM golang:alpine AS build
ARG VERSION

RUN apk add -qU git
WORKDIR /go/src
RUN mkdir -p github.com/OperatorFoundation \
  && cd github.com/OperatorFoundation \
  && git clone --branch $VERSION https://github.com/OperatorFoundation/shapeshifter-dispatcher.git --depth 1
WORKDIR /go/src/github.com/OperatorFoundation/shapeshifter-dispatcher/shapeshifter-dispatcher
RUN go get -v
RUN go build

FROM alpine:3
COPY --from=build /go/src/github.com/OperatorFoundation/shapeshifter-dispatcher/shapeshifter-dispatcher/shapeshifter-dispatcher /bin/shapeshifter-dispatcher
CMD shapeshifter-dispatcher
